Assignment1/Controllers/CompoundController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assignment1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Assignment1.Controllers
{
    public class CompoundController : Controller
    {
        public static Assignment1Context context;
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult CalculateCompoundValue(Compound cObj)
        {
            cObj.Result = cObj.Principal * (Math.Pow((1 + (cObj.Rate / cObj.Number)), (cObj.Number * cObj.Time)));
            return View(cObj);
        }
    }
}

Assignment1/Controllers/RoleManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assignment1.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Assignment1.Controllers
{
    public class RoleManagerController : Controller
    {
        private readonly Assignment1Context _context;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleManagerController(Assignment1Context context, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _roleManager = roleManager;
        }

        // GET: Cities
        public async Task<IActionResult> Index()
        {
            var roles = _roleManager.Roles;
            return View(await roles.ToListAsync());
        }

        // GET: Provinces/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var UserData = await _context.UserData
                .FirstOrDefaultAsync(m => m.Id == id);
            if (UserData == null)
            {
                return NotFound();
            }

            return View(UserData);
        }

        // GET: Provinces/Create
        public IActionResult Create()
        {
            return View();
        }
        // GET: Provinces/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var CurrentRole = await _roleManager.FindByIdAsync(id);
            if (CurrentRole == null)
            {
                return NotFound();
            }
            return View(CurrentRole);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var CurrentRole = await _roleManager.FindByIdAsync(id);
            await _roleManager.DeleteAsync(CurrentRole);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    
        // POST: Provinces/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] IdentityRole role)
        {
            if (ModelState.IsValid)
            {
                if (!await _roleManager.RoleExistsAsync(role.Name))
                {
                    await _roleManager.CreateAsync(new IdentityRole(role.Name));
                }
            }
            return RedirectToAction(nameof(Index));
        }


    }
}

Assignment1/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assignment1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Assignment1.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;


namespace Assignment1.Controllers
{
    public class UserManagerController : Controller
    {
        private readonly Assignment1Context _context;
        private readonly UserManager<Assignment1User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private string currentID;

        public UserManagerController(Assignment1Context context, RoleManager<IdentityRole> roleManager, UserManager<Assignment1User> userManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET: Cities
        public async Task<IActionResult> Index()
        {
            return View(await _context.UserData.ToListAsync());
        }

        // GET: Provinces/Details/5
        public async Task<IActionResult> DeleteUser(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var UserData = await _context.UserData
                .FirstOrDefaultAsync(m => m.Id == id);
            if (UserData == null)
            {
                return NotFound();
            }

            return View(UserData);
        }

        public async Task<IActionResult> ChangeUserRole(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var UserData = await _context.UserData
                .FirstOrDefaultAsync(m => m.Id == id);
            if (UserData == null)
            {
                return NotFound();
            }

            var IdentRole = await _context.IdentRole
                .FirstOrDefaultAsync(m => m.Id == id);
            if (UserData == null)
            {
                return NotFound();
            }
            
            var val = await _context.IdentRole
                .FirstOrDefaultAsync();

    
            //System.Diagnostics.Debug.WriteLine(roleManager.Roles);
            
           
            var CurrentRole = await _userManager.GetRolesAsync(UserData);
            this.currentID = id;

            System.Diagnostics.Debug.WriteLine("here yo");
            UserSpecs specs = new UserSpecs();
            specs.AvailableRoles = _roleManager.Roles.ToList();
            specs.CurrentRole = CurrentRole.ToList();
            var modelCollection = new ModelContainer();
            modelCollection.AddModel(UserData);
            modelCollection.AddModel(specs);
            return View(modelCollection);
        }

        // GET: Provinces/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Provinces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var CurrentUser = await _userManager.FindByIdAsync(id);
            await _userManager.DeleteAsync(CurrentUser);
            return RedirectToAction(nameof(Index));
        }

        // POST: Provinces/Delete/5
        [HttpPost, ActionName("RemoveFromRole")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveFromRoleConfirmed(string item, string id)
        {
            System.Diagnostics.Debug.WriteLine("here");
            System.Diagnostics.Debug.WriteLine(item);
            System.Diagnostics.Debug.WriteLine(id);
            var CurrentUser = await _userManager.FindByIdAsync(id);
            await _userManager.RemoveFromRoleAsync(CurrentUser, item);
            return RedirectToAction(nameof(Index));
        }


        // POST: Provinces/Delete/5
        [HttpPost, ActionName("Save")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveConfirmed(string id)
        {
            string newRole = Request.Form["selectedRole"];
            System.Diagnostics.Debug.WriteLine(newRole);
            var currentUser = await _userManager.FindByIdAsync(id);
            var roles = await _userManager.GetRolesAsync(currentUser);
            //await _userManager.RemoveFromRolesAsync(currentUser, roles.ToArray());
            var userRoles = await _userManager.GetRolesAsync(currentUser);
            bool alreadyInrole = false;
            foreach(var item in userRoles.ToList())
            {
                if(item.Equals(newRole))
                {
                    alreadyInrole = true;
                }
            }

            if(!alreadyInrole)
            {
                await _userManager.AddToRoleAsync(currentUser, newRole);
            }
            return RedirectToAction(nameof(Index));
        }

        private bool ProvinceExists(string id)
        {
            return _context.UserData.Any(e => e.Id == id);
        }

    }
}

Assignment1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Assignment1.Areas.Identity.Data

@inject SignInManager<Assignment1User> SignInManager
@inject UserManager<Assignment1User> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Assignment1</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-area="" asp-controller="Compound" asp-action="Index">Compound Calculator</a></li>
                    }
                    @if (SignInManager.IsSignedIn(User))
                    {
                        @if (User.IsInRole("Admin"))
                        {
                            <li><a asp-area="" asp-controller="RoleManager" asp-action="Index">Role Manager</a></li>
                            <li><a asp-area="" asp-controller="UserManager" asp-action="Index">User Manager</a></li>
                        }
                    }
                    </ul>
                <!--<partial name="_LoginNav" />-->
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Assignment1</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Assignment1/Views/Shared/_loginNav.cshtml
@using Microsoft.AspNetCore.Identity
@using Assignment1.Areas.Identity.Data
@inject SignInManager<Assignment1User> SignInManager
@inject UserManager<Assignment1User> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/Index", new { area = "" })" method="post" id="logoutForm" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @UserManager.GetUserName(User)</a>
            </li>
            <li>
                <button type="submit" class="btn btn-link navbar-btn navbar-link">Logout</button>
            </li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a asp-area="Identity" asp-page="/Account/Register">Register</a></li>
        <li><a asp-area="Identity" asp-page="/Account/Login">Login</a></li>
    </ul>
}